language: python
python: "3.9-dev"

sudo: required

services:
  - docker

before_script:
  - docker build -t francescoracciatti/pokedex -f Dockerfile .
  - docker run -d -p 6000:6000 francescoracciatti/pokedex
  - cd test

script:
  - travis_wait 30 sleep infinity &
  - python test_api.py --host 127.0.0.1 --port 6000 TestAPI