language: python
python: "3.9-dev"

sudo: required

services:
  - docker

env:
  jobs:
    - USE_NETWORK=true

before_install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: run server
      script:
        - cd src
        - export FLASK_APP=pokedex
        - flask run --host=0.0.0.0 --port=6000

    - stage: test
      script:
        - cd test
        - python test_api.py --host 127.0.0.1 --port 6000 TestAPI