language: python
python: "3.9-dev"

sudo: required

services:
  - docker

env:
  jobs:
    - USE_NETWORK=true

before_install:
  - pip install -r requirements.txt
  - pip install -e .

jobs:
  include:
    - stage: run server
      script:
        - docker build --tag francescoracciatti/pokedex .
        - docker run -d -p 6000:6000 francescoracciatti/pokedex

    - stage: test
      script:
        - cd test
        - python test_api.py --host 127.0.0.1 --port 6000 TestAPI