language: python
python: "3.10"

sudo: required

services:
  - docker

before_install:
  - docker build -t francescoracciatti/pokedex -f Dockerfile .

before_script:
  - docker run -d -p 6000:6000 francescoracciatti/pokedex
  - cd test

script:
  - python test_api.py --host 127.0.0.1 --port 6000 TestAPI