language: python
python: "3.9-dev"

sudo: required

services:
  - docker

env:
  jobs:
    - USE_NETWORK=true

before_script:
  - docker build -t francescoracciatti/pokedex -f Dockerfile .
  - docker run -d -p 6000:6000 francescoracciatti/pokedex
  - travis_wait 30 sleep infinity &
  - cd test
  - docker build -t francescoracciatti/test -f Dockerfile .

script:
  - docker run francescoracciatti/test