language: python

sudo: required
services:
  - docker

before_install:
  - docker build -t francescoracciatti/pokedex -f Dockerfile .

before_script:
  - docker run -d -p 6000:6000 francescoracciatti/pokedex

script:
  - cd test && python test_api.py --host 127.0.0.1 --port 6000 TestAPI